# Numpy exercises


#### 1. Import the numpy package under the name `np` (★☆☆) `hint: import … as`

In [ ]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆) `hint: vector is a single raw array`

In [1]:
import numpy as np
s = np.zeros(10)
print(s)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. How to find the memory size of any array, creat a random 5x6 array and check the sizs (★☆☆)

In [81]:
s = np.array(5)
s(np.itemsize)

AttributeError: ignored

#### 4. How to get the documentation of the numpy add function from the command line? (★☆☆) `hint: use info or ?`

In [8]:
import numpy as np
print(np.info(np.add))
np?

None


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆) `hint: array[x]`

In [7]:
import numpy as np
s=np.zeros(10)
s[4]=1
print(s)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector (single raw array) with values ranging from 10 to 49 (★☆☆) `hint: arange`

In [12]:
import numpy as np
s=np.arange(10,50)
print (s)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Show how you can Reverse a vector (first element becomes last) (★☆☆)`hint: use index of -1`

In [13]:
s = np.arange(1,20)
s= s[::-1]
print (s)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) `hint: use range and reshape!`

In [14]:
s = np.arange(9).reshape(3,3)
print (s)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆) `hint: use the np.nonzero`

In [15]:
import numpy as np
s= np.nonzero([1,2,0,0,4,0])
print(s)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) `hint: use index and use np.eye`
the following is an example of 5x4 identity matrix


```
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

```



In [20]:
import numpy as np
s= np.eye(3,3)
print (s)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) `hint: np.random.random`

In [25]:
import numpy as np
s=np.random.random(3,3,3)
print(s)

TypeError: ignored

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) `hint: min, max`

In [26]:
s = np.random.random((10,10))
Saja , Sara = s.min(), s.max()
print(Saja, Sara)

0.000747910036609456 0.9897209153750884


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) `hint: mean`

In [27]:
s = np.random.random(10)
saja = s.mean()
print (s)


[0.51139912 0.3935483  0.64760733 0.68168364 0.64592816 0.65427478
 0.23918201 0.27741338 0.48851714 0.81551674]


#### 15. Create a 2d array as following, with 1 on the border and 0 inside.. see generated array (★☆☆)



```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```



In [38]:
import numpy as np
S = np.ones((10,10))
S[1:-1,1:-1] = 0
print(S)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★★☆) `hint: see generated array np.pad   `

In [44]:
import numpy as np
S = np.ones((3,3))
S = np.pad(S, pad_width=1, mode='constant', constant_values=0)
print(S)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [39]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


 ####18  What is the result of the following expression? (★☆☆) `hint: indexing the nan using np.nan`



```
Z = np.ones((5,5))
Z[0,1]=np.nan
Z
```



In [29]:
Z = np.ones((5,5))
Z[0,1]=np.nan
print(Z)

[[ 1. nan  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


#### 18. Now, use this expression to find the index of your nan


```
np.argwhere(x!=x)    Hint: x is your array
```





In [48]:
s = np.array([[2,2,2,2,2],
              [4,4,np.nan,4,4],
              [np.nan,6,6,6,6]])
np.argwhere(np.isnan(s))
print(s)

[[ 2.  2.  2.  2.  2.]
 [ 4.  4. nan  4.  4.]
 [nan  6.  6.  6.  6.]]


20. Generate the following array 


```
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
```



In [55]:
import numpy as np
s = np.arange(15).reshape(3, 5)
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### 19. Extract the following values `array([ 1,  6, 11, 16])`. ` Hint: use np.diagonal()`

In [58]:
import numpy as np
s = np.arange(15).reshape(3, 5)
s(np.diagonal(s, offset=0 , asxis1=0 , axis2=1))
s

TypeError: ignored

array([7.29e-44, 1.96e-44, 2.80e-45, 1.35e-43, 5.75e-44, 9.95e-44,
       9.25e-44, 7.85e-44, 6.31e-44, 5.61e-45], dtype=float32)

#### 20. Try to use `np.diag` to Create a 5x5 matrix with diagonal values 11,11,11,11 (★★☆) Hint: use np.diag with k=0 and [11,11,11,11]. -- diag([11,11,11,11],k=-0)

#### 21.  Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) `Hint: use k=-1 when calling np.diag`

In [82]:
import numpy as np
s = np.diag([1, 2, 3, 4, 5])
print(s)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


####22. Create a 8x8 matrix and fill it with a given pattern (★☆☆) Hint: use np.zeros and do the replace 



```
[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]
```



In [66]:
s = np.zeros ((8,8), dtype=str)
s[1::2, ::2]= 'M'
s[::2, 1::2] = 'O'
print (s)

[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]


#### 23. Use the `np.tile` to generate the same pattern 

```
[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]
```



In [69]:
array= np.array([['O','M'], ['M','O']])
S = np.tile(array,(3,4))
print (S)

[['O' 'M' 'O' 'M' 'O' 'M' 'O' 'M']
 ['M' 'O' 'M' 'O' 'M' 'O' 'M' 'O']
 ['O' 'M' 'O' 'M' 'O' 'M' 'O' 'M']
 ['M' 'O' 'M' 'O' 'M' 'O' 'M' 'O']
 ['O' 'M' 'O' 'M' 'O' 'M' 'O' 'M']
 ['M' 'O' 'M' 'O' 'M' 'O' 'M' 'O']]


#### 24. Generate then Normalize a 5x5 random matrix (★☆☆)  `hint: Normalization_array = (x_arr -mean_value(x))/std_value(x)`

In [71]:
import numpy as np
x = np.random.random((5,5))
print('array:')
print(x) 
xmin, xmax = x.min(), x.max()
print(xmin, xmax)

array:
[[0.97883744 0.76931857 0.12647612 0.16089099 0.42842335]
 [0.81942754 0.86527965 0.22130482 0.19479602 0.71586563]
 [0.84223378 0.06598563 0.57140578 0.925617   0.15406081]
 [0.78318247 0.868687   0.62954085 0.04847927 0.12148   ]
 [0.38466839 0.5129705  0.56526776 0.41818424 0.66672993]]
0.04847927256228779 0.9788374419973229


#### 25. generate any 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

where 

```
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
```
will return

```
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
```




In [ ]:
Z = np.arange(11)
# Your code here!. 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 26. Consider an integer vector Z, comment any iligal expressions (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [73]:
Z = 10
print(Z**Z)

print(2 << Z >> 2)

print(Z <- Z)

print(1j*Z)

print(Z/1/1)

print(Z<Z>Z)

10000000000
512
False
10j
10.0
False


#### 27. Generate two randon 1D array, How to find common values between two arrays? (★☆☆) `Hint: use intersect1d(Arr1,Arr2)`

#### 28. How to ignore all numpy warnings (not recommended)? (★☆☆)

####29. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [75]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
